### ISSUE TITLE
iojs QueryString escape bug

### ISSUE THREAD

**Issue by willin** [qiniu/nodejs-sdk.v6#133]
Error report

```
TypeError: undefined is not a function
    at Object.QueryString.escape (querystring.js:101:13)
    at Object.makeBaseUrl (/Users/willin/app/node_modules/qiniu/qiniu/rs.js:242:29)
    at downloadAction (/Users/willin/app/App/Lib/Controller/Version/LogController.js:44:27)
    at /Users/willin/app/node_modules/thinkjs/lib/Lib/Core/App.js:118:30
```

file at `qiniu/qiniu/rs.js`

line **243**

```
// query like '-thumbnail', '?imageMogr2/thumbnail/960x' and so on
function makeBaseUrl(domain, key, query) {
  key = new Buffer(key);
  return 'http://' + domain + '/' + querystring.escape(key) + (query||'');
}
```

Escape param should be a string.

```
// query like '-thumbnail', '?imageMogr2/thumbnail/960x' and so on
function makeBaseUrl(domain, key, query) {
  //key = new Buffer(key);
  return 'http://' + domain + '/' + querystring.escape(key) + (query||'');
}
```

will be ok.

**Comment by longbai** [comment]
收到，我看下

**Comment by willin** [comment]
@longbai  也许这个问题是由于 io.js 1.6.0 querystring的一些缺陷引起.
在1.6.1 CHANGELOG上看到修复一些问题不知道是否对其产生影响

**Comment by forrest-mao** [comment]
@willin 用2.4.0的io.js目前测试没有出现类似的异常反馈，可以尝试做下升级
