### ISSUE TITLE
no such bucket

### ISSUE THREAD

**Issue by Fov6363** [qiniu/nodejs-sdk.v6#207]
之前是好用的,今天突然上传文件报这个错,新建bucket也无效,相关代码如下:

`function uploadFile(key,localFile,cb) {
    //需要填写你的 Access Key 和 Secret Key
    qiniu.conf.ACCESS_KEY = config['access_key'];
    qiniu.conf.SECRET_KEY = config['secret_key'];
    //要上传的空间
    const bucket = config['bucket'];
    //baas bucket的url前缀
    const url_pre = config['url_pre'];

    if(typeof key != 'string'){
        key += '';
    }

    let token = uptoken(bucket,key);
    let extra = new qiniu.io.PutExtra();
    qiniu.io.putFile(token,key,localFile,extra,function (err,ret) {
        cb(err,url_pre + key);
    });

}`

报错信息如下:
`Error: Server responded with status code 631:
{"error":"no such bucket"}
    at Object.exports.up_host (/Users/yuanyuan/git/nodejs_api/node_modules/qiniu/qiniu/zone.js:54:19)
    at putReadable (/Users/yuanyuan/git/nodejs_api/node_modules/qiniu/qiniu/io.js:55:8)
    at Object.putFile (/Users/yuanyuan/git/nodejs_api/node_modules/qiniu/qiniu/io.js:120:10)
    at uploadFile (/Users/yuanyuan/git/nodejs_api/models/qiniu.js:43:14)
    at Object.<anonymous> (/Users/yuanyuan/git/nodejs_api/models/qiniu.js:51:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
`

补充一下,最近做了次七牛的https升级,但代码没有动,会不会这方面的原因.

**Comment by Fov6363** [comment]
我的AK/SK更换了,导致会出这个错.
